#!/usr/bin/env bash
# Runs automatically on Codespace creation (non-interactive).
# Installs tools (tmux, gh, Claude Code), project dependencies,
# creates directories, and generates a config-only .env.
set -euo pipefail

echo ""
echo "=== Installing system tools ==="

# --- tmux ---
if ! command -v tmux &>/dev/null; then
  echo "Installing tmux..."
  sudo apt-get update -qq && sudo apt-get install -y -qq tmux
  echo " ✅ tmux installed"
else
  echo " ✅ tmux already installed ($(tmux -V))"
fi

# --- gh CLI (fallback – also provided by devcontainer feature) ---
if ! command -v gh &>/dev/null; then
  echo "Installing GitHub CLI..."
  sudo apt-get update -qq && sudo apt-get install -y -qq gh
  echo " ✅ gh installed"
else
  echo " ✅ gh already installed ($(gh --version | head -1))"
fi

# --- Claude Code ---
if ! command -v claude &>/dev/null; then
  echo "Installing Claude Code..."
  npm install -g @anthropic-ai/claude-code
  echo " ✅ Claude Code installed"
else
  echo " ✅ Claude Code already installed ($(claude --version 2>/dev/null || echo 'unknown version'))"
fi

# --- Google Workspace CLI ---
if ! command -v gws &>/dev/null; then
  echo "Installing Google Workspace CLI..."
  npm install -g @googleworkspace/cli
  echo " ✅ gws installed"
else
  echo " ✅ gws already installed ($(gws --version 2>/dev/null || echo 'unknown version'))"
fi

echo ""
echo "=== Installing project dependencies ==="

# Install project dependencies
echo "Installing project dependencies..."
npm install

# Codespace-appropriate paths
WORK_DIR="/workspaces/claude-code-agent/workspace"
MEMORY_DIR="/workspaces/claude-code-agent/.claude-agent/memory"
CLAUDE_AGENT_DIR="/workspaces/claude-code-agent/.claude-agent"

# Create required directories
mkdir -p "$WORK_DIR" "$MEMORY_DIR"

# Generate config-only .env (secrets added later via setup-secrets.sh)
if [ ! -f .env ]; then
    cat > .env <<EOF
# === Config (generated by post-create.sh) ===
PORT=8080
CLAUDE_MODEL=claude-haiku-4-5-20251001
CLAUDE_MAX_TURNS=25
CLAUDE_MAX_BUDGET_USD=5
CLAUDE_WORK_DIR=${WORK_DIR}
MEMORY_DIR=${MEMORY_DIR}
GOOGLE_WORKSPACE_CLI_CREDENTIALS_FILE=${CLAUDE_AGENT_DIR}/google-service-account.json

# === Secrets ===
# Run: bash .devcontainer/setup-secrets.sh
# to inject secrets from Bitwarden vault.
EOF
    chmod 600 .env
    echo "Generated .env with config defaults."
else
    echo ".env already exists, skipping generation."
fi

# --- Add bash aliases ---
BASHRC="$HOME/.bashrc"
if ! grep -q "alias claudy=" "$BASHRC" 2>/dev/null; then
  echo "" >> "$BASHRC"
  echo "# Claude Code aliases (added by devcontainer setup)" >> "$BASHRC"
  echo "alias claudy='claude --dangerously-skip-permissions'" >> "$BASHRC"
  echo " ✅ Added alias: claudy -> claude --dangerously-skip-permissions"
else
  echo " ✅ Alias claudy already exists in .bashrc"
fi

# --- Create tmux convenience script ---
cat > .devcontainer/start-tmux.sh << 'TMUXEOF'
#!/usr/bin/env bash
# Quick-start tmux session with Claude Code + dev server
# Usage: bash .devcontainer/start-tmux.sh

SESSION="work"

if tmux has-session -t "$SESSION" 2>/dev/null; then
  echo "Attaching to existing tmux session '$SESSION'..."
  tmux attach -t "$SESSION"
else
  echo "Creating new tmux session '$SESSION'..."
  # Window 0: Claude Code
  tmux new-session -d -s "$SESSION" -n claude
  tmux send-keys -t "$SESSION:claude" "claude" Enter

  # Window 1: Dev server
  tmux new-window -t "$SESSION" -n dev
  tmux send-keys -t "$SESSION:dev" "npm run dev" Enter

  # Window 2: General terminal
  tmux new-window -t "$SESSION" -n shell

  # Focus on Claude window
  tmux select-window -t "$SESSION:claude"

  echo "tmux session '$SESSION' created with windows: claude, dev, shell"
  echo "Attaching..."
  tmux attach -t "$SESSION"
fi
TMUXEOF
chmod +x .devcontainer/start-tmux.sh

echo ""
echo "=== Setup complete ==="
echo "To inject secrets from Bitwarden, run:"
echo "  bash .devcontainer/setup-secrets.sh"
echo ""
echo "To start a tmux session with Claude Code + dev server:"
echo "  bash .devcontainer/start-tmux.sh"
echo ""
echo "Tmux cheat sheet:"
echo "  Ctrl+b d       → detach (session keeps running)"
echo "  Ctrl+b c       → new window"
echo "  Ctrl+b n / p   → next / previous window"
echo "  tmux attach     → reattach to session"
