#!/usr/bin/env bash
# Runs automatically on Codespace creation (non-interactive).
# Installs dependencies, creates directories, and generates a config-only .env.
set -euo pipefail

echo "=== Post-create setup ==="

# Install Bitwarden CLI for later secret injection
echo "Installing Bitwarden CLI..."
npm i -g @bitwarden/cli

# Install project dependencies
echo "Installing project dependencies..."
npm install

# Codespace-appropriate paths
WORK_DIR="/workspaces/claude-code-agent/workspace"
MEMORY_DIR="/workspaces/claude-code-agent/.claude-agent/memory"
CLAUDE_AGENT_DIR="/workspaces/claude-code-agent/.claude-agent"

# Create required directories
mkdir -p "$WORK_DIR" "$MEMORY_DIR"

# Generate config-only .env (secrets added later via setup-secrets.sh)
if [ ! -f .env ]; then
  cat > .env <<EOF
# === Config (generated by post-create.sh) ===
PORT=8080
CLAUDE_MODEL=claude-haiku-4-5-20251001
CLAUDE_MAX_TURNS=25
CLAUDE_MAX_BUDGET_USD=5
CLAUDE_WORK_DIR=${WORK_DIR}
MEMORY_DIR=${MEMORY_DIR}

# === Secrets ===
# Run: bash .devcontainer/setup-secrets.sh
# to inject secrets from Bitwarden vault.
EOF
  chmod 600 .env
  echo "Generated .env with config defaults."
else
  echo ".env already exists, skipping generation."
fi

echo ""
echo "=== Setup complete ==="
echo "To inject secrets from Bitwarden, run:"
echo "  bash .devcontainer/setup-secrets.sh"
