#!/usr/bin/env bash
# Sets up a development environment for the Axis Agent project.
# Works in both GitHub Codespaces and local machines.
#
# In Codespaces: runs automatically via postCreateCommand.
# Locally:       run manually: bash .devcontainer/post-create.sh
#
# What it does:
#   1. Installs tools: bw (Bitwarden CLI), tmux, gh, claude, gws
#   2. Installs npm dependencies
#   3. Generates a config-only .env (secrets added later via setup-secrets.sh)
#   4. Configures SSH proxy for Tailscale access to deployed instance
#
# After this script completes, run:
#   bash .devcontainer/setup-secrets.sh
# to inject secrets from Bitwarden vault.
set -euo pipefail

echo ""
echo "=== Installing system tools ==="

# --- Bitwarden CLI ---
# Needed for setup-secrets.sh. Devcontainer feature may provide it in Codespaces,
# but we install portably to ~/.local/bin as a fallback for any environment.
if ! command -v bw &>/dev/null; then
  echo "Installing Bitwarden CLI..."
  mkdir -p "$HOME/.local/bin"
  BW_URL="https://vault.bitwarden.com/download/?app=cli&platform=linux"
  curl -fsSL "$BW_URL" -o /tmp/bw.zip
  python3 -c "import zipfile; zipfile.ZipFile('/tmp/bw.zip').extractall('$HOME/.local/bin/')"
  chmod +x "$HOME/.local/bin/bw"
  rm -f /tmp/bw.zip
  # Ensure ~/.local/bin is on PATH for this session
  export PATH="$HOME/.local/bin:$PATH"
  echo " ✅ bw installed to ~/.local/bin ($(bw --version))"
else
  echo " ✅ bw already installed ($(bw --version))"
fi

# --- tmux ---
if ! command -v tmux &>/dev/null; then
  echo "Installing tmux..."
  if command -v sudo &>/dev/null && sudo -n true 2>/dev/null; then
    sudo apt-get update -qq && sudo apt-get install -y -qq tmux
  else
    echo "  SKIP: tmux requires sudo (optional — install manually if needed)"
  fi
else
  echo " ✅ tmux already installed ($(tmux -V))"
fi

# --- gh CLI (fallback – also provided by devcontainer feature) ---
if ! command -v gh &>/dev/null; then
  echo "Installing GitHub CLI..."
  if command -v sudo &>/dev/null && sudo -n true 2>/dev/null; then
    sudo apt-get update -qq && sudo apt-get install -y -qq gh
  else
    echo "  SKIP: gh requires sudo (optional — install manually if needed)"
  fi
else
  echo " ✅ gh already installed ($(gh --version | head -1))"
fi

# --- Claude Code ---
if ! command -v claude &>/dev/null; then
  if command -v npm &>/dev/null; then
    echo "Installing Claude Code..."
    npm install -g @anthropic-ai/claude-code
    echo " ✅ Claude Code installed"
  else
    echo "  SKIP: Claude Code requires npm (install Node.js 22+ first)"
  fi
else
  echo " ✅ Claude Code already installed ($(claude --version 2>/dev/null || echo 'unknown version'))"
fi

# --- Google Workspace CLI ---
if ! command -v gws &>/dev/null; then
  if command -v npm &>/dev/null; then
    echo "Installing Google Workspace CLI..."
    npm install -g @googleworkspace/cli
    echo " ✅ gws installed"
  else
    echo "  SKIP: gws requires npm (install Node.js 22+ first)"
  fi
else
  echo " ✅ gws already installed ($(gws --version 2>/dev/null || echo 'unknown version'))"
fi

echo ""
echo "=== Installing project dependencies ==="

# Install project dependencies
echo "Installing project dependencies..."
npm install

# Codespace-appropriate paths
WORK_DIR="/workspaces/claude-code-agent/workspace"
MEMORY_DIR="/workspaces/claude-code-agent/.claude-agent/memory"
CLAUDE_AGENT_DIR="/workspaces/claude-code-agent/.claude-agent"

# Create required directories
mkdir -p "$WORK_DIR" "$MEMORY_DIR"

# Generate config-only .env (secrets added later via setup-secrets.sh)
if [ ! -f .env ]; then
    cat > .env <<EOF
# === Config (generated by post-create.sh) ===
PORT=8080
CLAUDE_MODEL=claude-opus-4-6
CLAUDE_MAX_TURNS=25
CLAUDE_MAX_BUDGET_USD=5
CLAUDE_WORK_DIR=${WORK_DIR}
MEMORY_DIR=${MEMORY_DIR}
GOOGLE_WORKSPACE_CLI_CREDENTIALS_FILE=${CLAUDE_AGENT_DIR}/google-service-account.json

# === Retell (voice calling) ===
# RETELL_API_KEY=
# RETELL_PHONE_NUMBER=
# RETELL_AGENT_ID=

# === Secrets ===
# Run: bash .devcontainer/setup-secrets.sh
# to inject secrets from Bitwarden vault.
EOF
    chmod 600 .env
    echo "Generated .env with config defaults."
else
    echo ".env already exists, skipping generation."
fi

# --- Add bash aliases ---
BASHRC="$HOME/.bashrc"
if ! grep -q "alias claudy=" "$BASHRC" 2>/dev/null; then
  echo "" >> "$BASHRC"
  echo "# Claude Code aliases (added by devcontainer setup)" >> "$BASHRC"
  echo "alias claudy='claude --dangerously-skip-permissions'" >> "$BASHRC"
  echo "export GWS_TOKEN_CACHE_ENCRYPTION=false" >> "$BASHRC"
  echo " ✅ Added alias: claudy -> claude --dangerously-skip-permissions"
else
  echo " ✅ Alias claudy already exists in .bashrc"
fi

# --- Create tmux convenience script ---
cat > .devcontainer/start-tmux.sh << 'TMUXEOF'
#!/usr/bin/env bash
# Quick-start tmux session with Claude Code + dev server
# Usage: bash .devcontainer/start-tmux.sh

SESSION="work"

if tmux has-session -t "$SESSION" 2>/dev/null; then
  echo "Attaching to existing tmux session '$SESSION'..."
  tmux attach -t "$SESSION"
else
  echo "Creating new tmux session '$SESSION'..."
  # Window 0: Claude Code
  tmux new-session -d -s "$SESSION" -n claude
  tmux send-keys -t "$SESSION:claude" "claude" Enter

  # Window 1: Dev server
  tmux new-window -t "$SESSION" -n dev
  tmux send-keys -t "$SESSION:dev" "npm run dev" Enter

  # Window 2: General terminal
  tmux new-window -t "$SESSION" -n shell

  # Focus on Claude window
  tmux select-window -t "$SESSION:claude"

  echo "tmux session '$SESSION' created with windows: claude, dev, shell"
  echo "Attaching..."
  tmux attach -t "$SESSION"
fi
TMUXEOF
chmod +x .devcontainer/start-tmux.sh

# --- Configure Tailscale SSH proxy ---
# Tailscale in containers uses userspace networking, so direct TCP doesn't work.
# We use `tailscale nc` as an SSH ProxyCommand to route through DERP relay.
echo ""
echo "=== Configuring Tailscale SSH proxy ==="
mkdir -p "$HOME/.ssh"
if ! grep -q "Host claude-code-agent" "$HOME/.ssh/config" 2>/dev/null; then
  cat >> "$HOME/.ssh/config" << 'SSHEOF'

Host claude-code-agent
  HostName claude-code-agent
  User ubuntu
  IdentityFile ~/.ssh/claude-code-agent-key.pem
  ProxyCommand sudo tailscale nc %h %p
  StrictHostKeyChecking accept-new
SSHEOF
  chmod 600 "$HOME/.ssh/config"
  echo " ✅ SSH config for Tailscale proxy added"
else
  echo " ✅ SSH config for claude-code-agent already exists"
fi

echo ""
echo "=== Setup complete ==="
echo "Next steps:"
echo "  1. bash .devcontainer/setup-secrets.sh   — inject secrets from Bitwarden"
echo "  2. sudo tailscaled --tun=userspace-networking &  — start Tailscale daemon"
echo "  3. sudo tailscale up                     — authenticate to tailnet"
echo "  4. ./deploy.sh                           — deploy to instance"
echo ""
echo "To start a tmux session with Claude Code + dev server:"
echo "  bash .devcontainer/start-tmux.sh"
echo ""
echo "Tmux cheat sheet:"
echo "  Ctrl+b d       → detach (session keeps running)"
echo "  Ctrl+b c       → new window"
echo "  Ctrl+b n / p   → next / previous window"
echo "  tmux attach     → reattach to session"
