#!/usr/bin/env bash
# Inject secrets from Bitwarden vault into the local Codespace environment.
# Run manually after Codespace opens: bash .devcontainer/setup-secrets.sh
# Idempotent — safe to re-run.
set -euo pipefail

FOLDER_NAME="claude-agent-lightsail"
CLAUDE_AGENT_DIR="${CLAUDE_AGENT_DIR:-/workspaces/claude-code-agent/.claude-agent}"
CLAUDE_DIR="${CLAUDE_DIR:-$HOME/.claude}"

# Env var name -> Bitwarden item name
declare -A SECRET_MAP=(
  [TELEGRAM_BOT_TOKEN]="telegram-bot-token"
  [TELEGRAM_ALLOWED_USERS]="telegram-allowed-users"
  [GH_TOKEN]="gh-token"
  [ICAL_URL]="ical-url"
  [GOOGLE_MAPS_API_KEY]="google-maps-api-key"
  [FACEBOOK_APP_ID]="facebook-app-id"
  [FACEBOOK_APP_SECRET]="facebook-app-secret"
  [FACEBOOK_PAGE_ID]="facebook-page-id"
  [FACEBOOK_PAGE_TOKEN]="facebook-page-token-env"
  [COMPOSIO_API_KEY]="composio-api-key"
  [TRELLO_API_KEY]="trello-api-key"
  [TRELLO_API_TOKEN]="trello-api-token"
  [OWNTRACKS_TOKEN]="owntracks-token"
  [VAPI_API_KEY]="vapi-api-key"
  [VAPI_PHONE_NUMBER_ID]="vapi-phone-number-id"
  [CARTESIA_VOICE_ID]="cartesia-voice-id"
)

# JSON credential file mappings: BW item ID env var -> local path + label
declare -A JSON_CREDS=(
  [BW_GMAIL_ID]="./gmail_app_password.json|gmail"
  [BW_FACEBOOK_ID]="${CLAUDE_AGENT_DIR}/facebook-page-token.json|facebook"
  [BW_GOOGLE_SA_ID]="${CLAUDE_AGENT_DIR}/google-service-account.json|google-service-account"
  [BW_GOOGLE_CREDS_ID]="${CLAUDE_AGENT_DIR}/google-credentials.json|google-credentials"
)

# Optional JSON credentials
declare -A JSON_CREDS_OPTIONAL=(
  [BW_GOOGLE_CONTACTS_TOKEN_ID]="${CLAUDE_AGENT_DIR}/google-contacts-token.json|google-contacts-token"
  [BW_CLAUDE_OAUTH_ID]="${CLAUDE_DIR}/.credentials.json|claude-oauth"
)

# SSH key for deployment (looked up by name in vault, not by ID)
SSH_KEY_BW_NAME="lightsail-ssh-key"
SSH_KEY_PATH="$HOME/.ssh/claude-code-agent-key.pem"

# --- Bitwarden authentication ---
echo "=== Bitwarden Secret Injection ==="

if [ -z "${BW_SESSION:-}" ]; then
  if ! bw login --check &>/dev/null; then
    echo "Logging in to Bitwarden..."
    export BW_SESSION=$(bw login --raw)
  else
    echo "Unlocking Bitwarden vault..."
    export BW_SESSION=$(bw unlock --raw)
  fi
fi
bw sync

# Find the folder
FOLDER_ID=$(bw list folders --search "$FOLDER_NAME" | jq -r ".[] | select(.name==\"$FOLDER_NAME\") | .id")
if [ -z "$FOLDER_ID" ]; then
  echo "ERROR: Folder '$FOLDER_NAME' not found in vault." >&2
  exit 1
fi

# Fetch all items in the folder once
echo "Fetching items from '$FOLDER_NAME'..."
FOLDER_ITEMS=$(bw list items --folderid "$FOLDER_ID")

# --- Ensure .env exists ---
if [ ! -f .env ]; then
  echo "  .env not found — generating config defaults (run post-create.sh for full setup)"
  WORK_DIR="${CLAUDE_WORK_DIR:-/workspaces/claude-code-agent/workspace}"
  MEM_DIR="${MEMORY_DIR:-/workspaces/claude-code-agent/.claude-agent/memory}"
  cat > .env <<ENVEOF
# === Config (generated by setup-secrets.sh) ===
PORT=8080
CLAUDE_MODEL=claude-haiku-4-5-20251001
CLAUDE_MAX_TURNS=25
CLAUDE_MAX_BUDGET_USD=5
CLAUDE_WORK_DIR=${WORK_DIR}
MEMORY_DIR=${MEM_DIR}
GOOGLE_WORKSPACE_CLI_CREDENTIALS_FILE=${CLAUDE_AGENT_DIR}/google-service-account.json

# === Secrets ===
ENVEOF
  chmod 600 .env
fi

# --- Env secrets ---
echo "Injecting env secrets into .env..."
ENV_SECRETS=""
MISSING=()

for env_var in "${!SECRET_MAP[@]}"; do
  bw_name="${SECRET_MAP[$env_var]}"
  value=$(echo "$FOLDER_ITEMS" | jq -r ".[] | select(.name==\"$bw_name\") | .notes" 2>/dev/null || true)
  if [ -z "$value" ] || [ "$value" = "null" ]; then
    MISSING+=("$env_var ($bw_name)")
    continue
  fi
  ENV_SECRETS="${ENV_SECRETS}${env_var}=${value}\n"
done

if [ ${#MISSING[@]} -gt 0 ]; then
  echo "  WARN: Missing vault entries:"
  for m in "${MISSING[@]}"; do
    echo "    - $m"
  done
fi

if [ -n "$ENV_SECRETS" ]; then
  # Strip existing secret lines from .env
  SED_EXPR=""
  for env_var in "${!SECRET_MAP[@]}"; do
    SED_EXPR="${SED_EXPR}/^${env_var}=/d;"
  done
  if [ -n "$SED_EXPR" ]; then
    sed -i "${SED_EXPR}" .env
  fi

  # Append fresh secrets
  echo -e "$ENV_SECRETS" >> .env
  chmod 600 .env
  echo "  -> Env secrets merged into .env"
else
  echo "  WARN: No env secrets found in vault"
fi

# --- JSON credential files ---
echo "Injecting JSON credential files..."

mkdir -p "$CLAUDE_AGENT_DIR" "$CLAUDE_DIR"

write_json_cred() {
  local id_var="$1" path_label="$2"
  local item_id="${!id_var:-}"
  local path="${path_label%%|*}"
  local label="${path_label##*|}"

  if [ -z "$item_id" ]; then
    echo "  SKIP: $id_var not set ($label)"
    return
  fi

  local content
  content=$(bw get notes "$item_id")
  if [ -z "$content" ]; then
    echo "  WARN: '$label' is empty in vault, skipping"
    return
  fi

  mkdir -p "$(dirname "$path")"
  printf '%s\n' "$content" > "$path"
  chmod 600 "$path"
  echo "  -> $label -> $path"
}

for id_var in "${!JSON_CREDS[@]}"; do
  write_json_cred "$id_var" "${JSON_CREDS[$id_var]}"
done

for id_var in "${!JSON_CREDS_OPTIONAL[@]}"; do
  write_json_cred "$id_var" "${JSON_CREDS_OPTIONAL[$id_var]}"
done

# --- SSH key for deployment ---
echo "Injecting SSH deploy key..."
SSH_KEY_CONTENT=$(echo "$FOLDER_ITEMS" | jq -r ".[] | select(.name==\"$SSH_KEY_BW_NAME\") | .notes" 2>/dev/null || true)
if [ -n "$SSH_KEY_CONTENT" ] && [ "$SSH_KEY_CONTENT" != "null" ]; then
  mkdir -p "$(dirname "$SSH_KEY_PATH")"
  printf '%s\n' "$SSH_KEY_CONTENT" > "$SSH_KEY_PATH"
  chmod 600 "$SSH_KEY_PATH"
  echo "  -> SSH key -> $SSH_KEY_PATH"
else
  echo "  WARN: '$SSH_KEY_BW_NAME' not found in vault, skipping SSH key"
fi

# --- Google Workspace CLI (gws) OAuth token ---
echo "Injecting gws OAuth token..."
GWS_TOKEN_BW_NAME="gws-oauth-token"
GWS_CONFIG_DIR="$HOME/.config/gws"
GWS_TOKEN_CONTENT=$(echo "$FOLDER_ITEMS" | jq -r ".[] | select(.name==\"$GWS_TOKEN_BW_NAME\") | .notes" 2>/dev/null || true)
if [ -n "$GWS_TOKEN_CONTENT" ] && [ "$GWS_TOKEN_CONTENT" != "null" ]; then
  mkdir -p "$GWS_CONFIG_DIR"
  # Write credentials.json for gws CLI
  printf '%s\n' "$GWS_TOKEN_CONTENT" > "$GWS_CONFIG_DIR/credentials.json"
  chmod 600 "$GWS_CONFIG_DIR/credentials.json"
  # Also write client_secret.json from the same OAuth client config
  CLIENT_ID=$(echo "$GWS_TOKEN_CONTENT" | python3 -c "import sys,json; print(json.load(sys.stdin).get('client_id',''))" 2>/dev/null || true)
  CLIENT_SECRET=$(echo "$GWS_TOKEN_CONTENT" | python3 -c "import sys,json; print(json.load(sys.stdin).get('client_secret',''))" 2>/dev/null || true)
  if [ -n "$CLIENT_ID" ] && [ -n "$CLIENT_SECRET" ]; then
    python3 -c "
import json
cs = {'installed': {
    'client_id': '$CLIENT_ID',
    'client_secret': '$CLIENT_SECRET',
    'auth_uri': 'https://accounts.google.com/o/oauth2/auth',
    'token_uri': 'https://oauth2.googleapis.com/token',
    'redirect_uris': ['http://localhost']
}}
json.dump(cs, open('$GWS_CONFIG_DIR/client_secret.json', 'w'), indent=2)
"
    chmod 600 "$GWS_CONFIG_DIR/client_secret.json"
  fi
  echo "  -> gws OAuth token -> $GWS_CONFIG_DIR/credentials.json"
else
  echo "  WARN: '$GWS_TOKEN_BW_NAME' not found in vault, skipping gws token"
fi

# Add DEPLOY_HOST to .env if not already present
if ! grep -q '^DEPLOY_HOST=' .env 2>/dev/null; then
  echo "DEPLOY_HOST=ubuntu@54.66.167.208" >> .env
  echo "  -> DEPLOY_HOST added to .env"
fi

# --- Cleanup ---
bw lock
echo ""
echo "Done. Vault locked."
echo "Secrets injected. You can now run: npm run dev"
echo "To deploy: ./deploy.sh"
